### ISSUE TITLE
Unable to find a suitable version for purescript-typelevel-prelude

### ISSUE THREAD

**Issue by tarsbase** [owickstrom/hyper#87]
I was following the instruction from [Getting Started with Hyper¶
](https://hyper.wickstrom.tech/docs/v0.8.0/tutorials/getting-started-with-hyper.html) , but It showed me this after I type in '`bower i purescript-hyper --save`'

![EE81BDA8-80DF-4D8C-991A-67BF4DA09EA8](https://user-images.githubusercontent.com/33078987/63093067-6f9bec80-bf96-11e9-84a0-b64237aa11b3.png)

What should I do? 

Thanks

**Comment by nsaunders** [comment]
Unfortunately, this is a common situation with Bower and somewhat beyond our control since it is ultimately the result of upstream changes in dependencies. The quick fix for this is to resolve to (probably) option 2 or option 3 as prompted. However, I would also suggest looking into [spago](http://github.com/spacchetti/spago) or [psc-package](http://github.com/purescript/psc-package), which use curated "package sets" that avoid this issue.

If you are still having trouble, please feel free to reopen the issue.

**Comment by tarsbase** [comment]
Thanks @nsaunders :)
